site_name: Michigan Imputation Server
theme: readthedocs
pages:
- Home: index.md
- User Documentation:
  - Getting Started: getting-started.md
  - Data Preparation: prepare-your-data.md
  - Reference Panels: reference-panels.md
  - Pipeline Details: pipeline.md
  - Security: data-sensitivity.md
  - FAQ: faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
- Contact: contact.md

markdown_extensions:
    - toc:
        permalink:
    - admonition:
