site_name: Michigan Imputation Server
theme: readthedocs

pages:
- Home: index.md
- Getting Started: getting-started.md
- Data Preparation: prepare-your-data.md
- Reference Panels: reference-panels.md
- Pipeline Overview: pipeline.md
- Security: data-sensitivity.md
- FAQ: faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
  - Create Reference Panels: create-reference-panels.md
- Workshops:
  - ASHG2020: workshops/ASHG2020.md
  - ASHG2020 Job Submission: workshops/ASHG2020_Job_Submission.md
  - ASHG2020 Imputation Bot: workshops/ASHG2020_Imputation_Bot.md
- Contact: contact.md



repo_name: genepi/imputationserver
repo_url: https://github.com/genepi/imputationserver
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/genepi/imputationserver
    - type: twitter
      link: https://twitter.com/umimpute

markdown_extensions:
    - toc:
        permalink:
    - admonition:
