!cloudgene.mapred.util.Settings
name: Michigan Imputation Server - Public
apps:
  - id: imputationserver
    permission: user
    filename: applications/minimac/minimac-vcf.yaml
hadoopPath: /usr
removeHdfsWorkspace: true
streaming: false
secretKey: a-default-key