!cloudgene.mapred.util.Settings
name: UM Imputationserver-Docker
apps:
  - id: minimac
    permission: user
    filename: minimac/minimac-vcf.yaml
hadoopPath: /usr
hdfsWorkspace: cloudgene-workspace
https: false
mail: 
   port: 
   smtp: 
   name: 
   password: 
   user: 
maintenance: true
maxRunningJobs: 10
maxRunningJobsPerUser: 5
notificationAfter: 7
removeHdfsWorkspace: true
retireAfter: 10
streaming: false
streamingJar: /usr/contrib/streaming/hadoop-streaming-2.5.0-cdh5.3.1.jar
